# Generated by Django 4.2 on 2025-02-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="address1",
            new_name="shipping_address1",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="address2",
            new_name="shipping_address2",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="city",
            new_name="shipping_city",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="country",
            new_name="shipping_country",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="email",
            new_name="shipping_email",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="first_name",
            new_name="shipping_first_name",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="last_name",
            new_name="shipping_last_name",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="phone",
            new_name="shipping_phone",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="zipcode",
            new_name="shipping_zipcode",
        ),
    ]
