# Generated by Django 4.2 on 2025-01-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop_features", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Name",
            new_name="Product",
        ),
    ]
