# Generated by Django 4.2 on 2025-01-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shop_features",
            "0003_category_customer_product_description_product_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="sale_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
